// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsKc7nwme_LtXm9GEdV1ncOehSba_hs1I',
    appId: '1:429934915789:web:025d99405ab77d70543984',
    messagingSenderId: '429934915789',
    projectId: 'noteapp-ac4a3',
    authDomain: 'noteapp-ac4a3.firebaseapp.com',
    storageBucket: 'noteapp-ac4a3.appspot.com',
    measurementId: 'G-3CFRF7777P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4OoJC1i2xnh0Bp3Rvjkzp8tK0zTpXzug',
    appId: '1:429934915789:android:87422fcf96191bad543984',
    messagingSenderId: '429934915789',
    projectId: 'noteapp-ac4a3',
    storageBucket: 'noteapp-ac4a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmZdnl7mr2PeadlUzYZQPa8NmrfeVAyJc',
    appId: '1:429934915789:ios:72bf1a18bb395b8f543984',
    messagingSenderId: '429934915789',
    projectId: 'noteapp-ac4a3',
    storageBucket: 'noteapp-ac4a3.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmZdnl7mr2PeadlUzYZQPa8NmrfeVAyJc',
    appId: '1:429934915789:ios:3c9785d61bc6bbea543984',
    messagingSenderId: '429934915789',
    projectId: 'noteapp-ac4a3',
    storageBucket: 'noteapp-ac4a3.appspot.com',
    iosBundleId: 'com.example.noteApp.RunnerTests',
  );
}
